//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apterid.Bootstrap.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apterid.Bootstrap.Common.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node constructor&apos;s NodeArgs parameter must be named &quot;args&quot;..
        /// </summary>
        public static string E_0001_ParserImpl_MakeNodeArgs {
            get {
                return ResourceManager.GetString("E_0001_ParserImpl_MakeNodeArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A node constructor&apos;s Node[] parameter must be named &quot;children&quot;..
        /// </summary>
        public static string E_0002_ParserImpl_MakeNodeChildren {
            get {
                return ResourceManager.GetString("E_0002_ParserImpl_MakeNodeChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a constructor for {0}..
        /// </summary>
        public static string E_0003_ParserImpl_MakeNodeNoCtor {
            get {
                return ResourceManager.GetString("E_0003_ParserImpl_MakeNodeNoCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an output path..
        /// </summary>
        public static string E_0004_CmdLine_NoOutputPath {
            get {
                return ResourceManager.GetString("E_0004_CmdLine_NoOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown compiler output mode &apos;{0}&apos;..
        /// </summary>
        public static string E_0005_CmdLine_UnknownOutputMode {
            get {
                return ResourceManager.GetString("E_0005_CmdLine_UnknownOutputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file &apos;{0}&apos; cannot be found..
        /// </summary>
        public static string E_0006_Compiler_InvalidSourceFile {
            get {
                return ResourceManager.GetString("E_0006_Compiler_InvalidSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse..
        /// </summary>
        public static string E_0007_Parser_SyntaxError {
            get {
                return ResourceManager.GetString("E_0007_Parser_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate output file &apos;{0}&apos;..
        /// </summary>
        public static string E_0008_Compiler_DuplicateOutputFileInfo {
            get {
                return ResourceManager.GetString("E_0008_Compiler_DuplicateOutputFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate source file &apos;{0}&apos;..
        /// </summary>
        public static string E_0009_Analyzer_DuplicateSourceFile {
            get {
                return ResourceManager.GetString("E_0009_Analyzer_DuplicateSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file &apos;{0}&apos; is not valid source code..
        /// </summary>
        public static string E_0010_Analyzer_ParseTreeIsNotSource {
            get {
                return ResourceManager.GetString("E_0010_Analyzer_ParseTreeIsNotSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to have the construct &apos;{0}&apos; at the top level of a source file..
        /// </summary>
        public static string E_0011_Analyzer_InvalidToplevelItem {
            get {
                return ResourceManager.GetString("E_0011_Analyzer_InvalidToplevelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to bind to the name &apos;{0}&apos; more than once in one scope..
        /// </summary>
        public static string E_0012_Analyzer_DuplicateBinding {
            get {
                return ResourceManager.GetString("E_0012_Analyzer_DuplicateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to have the construct &apos;{0}&apos; here..
        /// </summary>
        public static string E_0013_Analyzer_InvalidScopeItem {
            get {
                return ResourceManager.GetString("E_0013_Analyzer_InvalidScopeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding &apos;{0}&apos; cannot be empty..
        /// </summary>
        public static string E_0014_Analyzer_EmptyBinding {
            get {
                return ResourceManager.GetString("E_0014_Analyzer_EmptyBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to infer type for expression &apos;{0}&apos;..
        /// </summary>
        public static string E_0015_Analyzer_UnableToInferType {
            get {
                return ResourceManager.GetString("E_0015_Analyzer_UnableToInferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory &apos;{0}&apos; does not exist or cannot be written to..
        /// </summary>
        public static string E_0016_Compiler_InvalidOutputDir {
            get {
                return ResourceManager.GetString("E_0016_Compiler_InvalidOutputDir", resourceCulture);
            }
        }
    }
}
